# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['start.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/*', 'config'),
        ('dialog/*', 'dialog'),
        ('main/*', 'main'),
        ('models/*', 'models'),
        ('pt/*', 'pt'),
        ('result/*', 'result'),
        ('test/*', 'test'),
        ('testdata/*', 'testdata'),
        ('utils/*', 'utils'),
        ('res_rc.py', '.'),
        ('MouseLabel.py', '.'),
        ('README.md', '.'),
        ('requirements.txt', '.'),
    ],
    hiddenimports=['mss', 'bokeh.server.tornado', 'mypy.checker', 'torch', 'ultralytics', 'MouseLabel'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt6'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='start',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)