# -*- coding: utf-8 -*-
import os
import sys
import threading

import mss
import numpy as np
# Form implementation generated from reading ui file 'innerface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#pyqt5库的引用
from PyQt5.QtCore import QResource, Qt, QTimer
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QMenu, QAction
from PyQt5.QtCore import Qt, QPoint, QTimer, QThread, pyqtSignal
from PyQt5.QtGui import QImage, QPixmap, QPainter, QIcon, QPalette, QBrush
#图像处理和深度学习相关的导入
import sys
import json
import numpy as np
import torch
import torch.backends.cudnn as cudnn
import os
import time
import cv2
import cv2 as CV2
from PyQt5.QtWebEngineWidgets import QWebEngineView
#Web引擎相关的导入
from MouseLabel import Label_click_Mouse
from main_win.wrjGPS import wrjGPS
from models.experimental import attempt_load
from test.captureScreen import boxScreen
from utils.augmentations import letterbox
from utils.datasets import LoadImages, LoadWebcam
from utils.CustomMessageBox import MessageBox
from utils.general import check_img_size, check_requirements, check_imshow, colorstr, non_max_suppression, \
    apply_classifier, scale_coords, xyxy2xywh, strip_optimizer, set_logging, increment_path
# from utils.plots import colors, plot_one_box, plot_one_box_PIL
from utils.plots import Annotator, colors, save_one_box
from utils.torch_utils import select_device
from utils.capnums import Camera
from dialog.rtsp_win import Window

img_src = np.zeros((1280, 720, 3), np.uint8)
COLORS = [
    (0, 0, 255), (255, 0, 0), (0, 255, 0), (255, 255, 0), (0, 255, 255),
    (255, 0, 255), (192, 192, 192), (128, 128, 128), (128, 0, 0),
    (128, 128, 0), (0, 128, 0)]
LABELS = ['', 'erosion', 'crack', 'sandhole']
img_src = cv2.imread('F:\science_study\sea win eletronic detect\data\selfCreate\images\\40.jpg')
tclose=False
truning=False
tsleep=False

